### ISSUE TITLE
last few requests for the proposal

### ISSUE THREAD

**Issue by egonw** [The-Marvex/GSoC_Proposal#13]
- [ ] https://github.com/The-Marvex/GSoC_Proposal/commit/f507b42fd632d0bc63d4993c323b1c83f3bd553e#commitcomment-33065360
- [ ] https://github.com/The-Marvex/GSoC_Proposal/commit/f507b42fd632d0bc63d4993c323b1c83f3bd553e#commitcomment-33065368

Please don't forget to submit the proposal :)

**Comment by m4na5** [comment]
I have made a comment regarding the same.
