### ISSUE TITLE
[URGENT] Mark proposal as FINAL

### ISSUE THREAD

**Issue by egonw** [The-Marvex/GSoC_Proposal#14]
Plz, don't wait until the last moment, and note Alex's comment on the SoC website.

**Comment by m4na5** [comment]
I have marked proposal as final on the SoC website. But I cannot find Alex's comment anywhere there.

**Comment by egonw** [comment]
ok, thanks! The next steps are now:

- wait for the ranking by NRNB mentors
- wait for the final number of positions NRNB gets from Google
