### ISSUE TITLE
more feedback on your proposal

### ISSUE THREAD

**Issue by egonw** [The-Marvex/GSoC_Proposal#5]
See my comments here: https://github.com/The-Marvex/GSoC_Proposal/commit/f507b42fd632d0bc63d4993c323b1c83f3bd553e

Overall, I think there is plenty that needs improvement for it to be selected:

- there are a number of inconsistencies
- more detail should be added (e.g. about FAIR output)
- needs better risk analysis
- lacking a clear plan on how you plan to communicate with developers and (importantly) users of BridgeDb

**Comment by The-Marvex** [comment]
Hello Sir,
I have made some changes as per your suggestions, I would like you to review them.

**Comment by egonw** [comment]
I will do that today. Can you also please send the link as a reply to your introduction email to the BridgeDb mailing list, and ask people there for feedback?

**Comment by egonw** [comment]
OK, not yesterday, but today or tomorrow.
